//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonLibs.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonLibs.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Type.
        /// </summary>
        public static string BrowserType {
            get {
                return ResourceManager.GetString("BrowserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser url.
        /// </summary>
        public static string BrowserUrl {
            get {
                return ResourceManager.GetString("BrowserUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chrome.
        /// </summary>
        public static string ChromeType {
            get {
                return ResourceManager.GetString("ChromeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edge.
        /// </summary>
        public static string EdgeType {
            get {
                return ResourceManager.GetString("EdgeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login action failed.
        /// </summary>
        public static string ErrorLogin {
            get {
                return ResourceManager.GetString("ErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist hasn&apos;t been created.
        /// </summary>
        public static string ErrorPlaylistNotCreate {
            get {
                return ResourceManager.GetString("ErrorPlaylistNotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist hasn&apos;t been deleted.
        /// </summary>
        public static string ErrorPlaylistNotDelete {
            get {
                return ResourceManager.GetString("ErrorPlaylistNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist hasn&apos;t been reproduced.
        /// </summary>
        public static string ErrorPlaylistNotReproduce {
            get {
                return ResourceManager.GetString("ErrorPlaylistNotReproduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string ExpectedFacebookTitle {
            get {
                return ResourceManager.GetString("ExpectedFacebookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify – Reproductor web.
        /// </summary>
        public static string ExpectedSpotifyTitle {
            get {
                return ResourceManager.GetString("ExpectedSpotifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename already exists.
        /// </summary>
        public static string FileExists {
            get {
                return ResourceManager.GetString("FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firefox.
        /// </summary>
        public static string FirefoxType {
            get {
                return ResourceManager.GetString("FirefoxType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid browser type.
        /// </summary>
        public static string InvalidBrowserType {
            get {
                return ResourceManager.GetString("InvalidBrowserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selenium Automation Playlist.
        /// </summary>
        public static string NewPlaylist {
            get {
                return ResourceManager.GetString("NewPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more step failed.
        /// </summary>
        public static string OneOrMoreStepFiled {
            get {
                return ResourceManager.GetString("OneOrMoreStepFiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing create playlist test.
        /// </summary>
        public static string PerformingCreatePlaylistTest {
            get {
                return ResourceManager.GetString("PerformingCreatePlaylistTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing delete playlist test.
        /// </summary>
        public static string PerformingDeletePlaylistTest {
            get {
                return ResourceManager.GetString("PerformingDeletePlaylistTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing drag and drop test.
        /// </summary>
        public static string PerformingDragAndDrop {
            get {
                return ResourceManager.GetString("PerformingDragAndDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing login.
        /// </summary>
        public static string PerformingLogin {
            get {
                return ResourceManager.GetString("PerformingLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing reproduce playlist test.
        /// </summary>
        public static string PerformingReproducePlaylistTest {
            get {
                return ResourceManager.GetString("PerformingReproducePlaylistTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify create playlist test.
        /// </summary>
        public static string VerifyCreatePlaylistTest {
            get {
                return ResourceManager.GetString("VerifyCreatePlaylistTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify delete playlist test.
        /// </summary>
        public static string VerifyDeletePlaylistTest {
            get {
                return ResourceManager.GetString("VerifyDeletePlaylistTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify login test.
        /// </summary>
        public static string VerifyLoginTest {
            get {
                return ResourceManager.GetString("VerifyLoginTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify reproduce playlist test.
        /// </summary>
        public static string VerifyReproducePlaylistTest {
            get {
                return ResourceManager.GetString("VerifyReproducePlaylistTest", resourceCulture);
            }
        }
    }
}
